# theme: jekyll-theme-minimal
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Brandon Lum
tagline:          "A personal blog focused around security and computation"
description:      "A personal blog focused around security and computation"
url:              https://lumjjb.github.io
baseurl:          /

author:
  name:           'TBD'
  url:            https://twitter.com/

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lumjjb/

collections:
  authors:
    output: true

defaults:
- scope:
    path: ""
    type: authors
  values:
    picture: "default.png" 
